### ISSUE TITLE
create SPARQL query to retrieve dataset

### ISSUE THREAD

**Issue by MarcZimmermann** [WorldHealthOrganization/xform-covid-casecount-wom#148]
### description:

in order to find a dataset in the web of data - a proper SPARQL query needs to be executed.

### tasks:

- [ ] load void.ttl into triple store
- [ ] query triple store to find dataset
- [ ] document as test case
- [ ] hand over documentation to **team infrastructure**
